export const LOG_USER_IN = "LOG_USER_IN";
export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const MY_COURSES_SUCCESS = "MY_COURSES_SUCCESS";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_ONE_COURSE_SUCCESS = "GET_ONE_COURSE_SUCCESS";
